# Generated by Django 5.2.8 on 2025-11-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedSalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(max_length=20)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('items_sold', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_summaries', to='inventory.branch')),
            ],
            options={
                'unique_together': {('period_start', 'period_end', 'period_type', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='products.product')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'related_product')},
            },
        ),
    ]
