# Generated by Django 5.2.8 on 2025-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_url',
            field=models.TextField(blank=True),
        ),
    ]
